;; Generated by Gemini 3!
;; Started with 3 functions, one by one:
;; - my/create-java-item
;; - my/create-java-test
;; - my/toggle-java-test-and-source
;; Then refactor all togehter, and followed by a few manual tweaks

(defun my--java-get-roots (root)
  "Return a list of (source-root test-root) for the given project ROOT."
  (list (expand-file-name "src/main/java/" root)
        (expand-file-name "src/test/java/" root)))

(defun my--java-path-to-package (path source-root)
  "Convert a file PATH to a Java package name relative to SOURCE-ROOT."
  (let* ((relative (file-relative-name (file-name-directory path) source-root))
         (clean-rel (directory-file-name relative)))
    (if (member clean-rel '("." "./" ""))
        nil
      (replace-regexp-in-string "/" "." clean-rel))))

(defun my/create-java-item (type-char input-path)
  "Create a Java item (class, interface, etc.) using dot notation for
sub-packages."
  (interactive
   (list (car (read-multiple-choice
               "Type: "
               '((?c "class")
                 (?i "interface")
                 (?e "enum")
                 (?r "record"))))
         (read-string "Name (e.g. models.User): ")))
  (let* ((type (cdr (assoc
                     type-char
                     '((?c . "class")
                       (?i . "interface")
                       (?e . "enum")
                       (?r . "record")))))
         (root (project-root (project-current t)))
         (src-root (car (my--java-get-roots root)))
         (normalized-path (replace-regexp-in-string "\\." "/" input-path))
         (full-path (expand-file-name (concat normalized-path ".java")
                                      (if (string-prefix-p src-root default-directory)
                                          default-directory src-root)))
         (item-name (file-name-nondirectory (file-name-sans-extension full-path))))

    (make-directory (file-name-directory full-path) t)
    (find-file full-path)
    (when (= (buffer-size) 0)
      (let ((pkg (my--java-path-to-package full-path src-root)))
        (when pkg (insert (format "package %s;\n\n" pkg)))
        (insert (format "public %s %s {\n\n    \n}" type item-name))
        (forward-line -2)
        (indent-according-to-mode)))))

(defun my/toggle-java-test-and-source ()
  "Jump between source and test. If test is missing, offer to create it."
  (interactive)
  (let* ((file (buffer-file-name))
         (root (project-root (project-current t)))
         (roots (my--java-get-roots root))
         (src-root (car roots))
         (test-root (cadr roots))
         target)
    (cond
     ((string-prefix-p src-root file)
      (setq target (replace-regexp-in-string (regexp-quote src-root) test-root file))
      (setq target (replace-regexp-in-string "\\.java$" "Test.java" target)))
     ((string-prefix-p test-root file)
      (setq target (replace-regexp-in-string (regexp-quote test-root) src-root file))
      (setq target (replace-regexp-in-string "Test\\.java$" ".java" target))))

    (cond
     ((and target (file-exists-p target)) (find-file target))
     ((and target (string-match-p "Test\\.java$" target))
      (when (y-or-n-p "Test file doesn't exist. Create it?")
        (my/create-java-test)))
     (t (message "Target not found or not in a standard Maven/Gradle layout.")))))

(defun my/create-java-test ()
  "Create a JUnit test class for the current file using a template."
  (interactive)
  (let* ((file (buffer-file-name))
         (root (project-root (project-current t)))
         (roots (my--java-get-roots root))
         (src-root (car roots))
         (test-root (cadr roots))
         (template (expand-file-name "templates/java-test.template" user-emacs-directory)))

    (unless (string-prefix-p src-root file) (error "Not in src/main/java/"))

    (let* ((rel-path (file-relative-name file src-root))
           (class-name (file-name-sans-extension (file-name-nondirectory rel-path)))
           (test-name (concat class-name "Test"))
           (target (expand-file-name (concat (file-name-directory rel-path) test-name ".java") test-root))
           (pkg (my--java-path-to-package file src-root)))

      (make-directory (file-name-directory target) t)
      (find-file target)
      (when (and (= (buffer-size) 0) (file-exists-p template))
        (insert (format (with-temp-buffer (insert-file-contents template) (buffer-string))
                        pkg test-name))
        (indent-region (point-min) (point-max))
        (goto-char (point-min))
        (when (search-forward "// given" nil t) (forward-line 1) (back-to-indentation))))))

(provide 'java-utils)
